const SETS=[{id:"base1",name:"Base",page:0},{id:"base2",name:"Jungle",page:0},{id:"base3",name:"Fossil",page:0},{id:"base5",name:"Team Rocket",page:1},{id:"gym2",name:"Gym Challenge",page:1}];
const PAGES=[{title:"Classic Sets",subtitle:"Base • Jungle • Fossil"},{title:"Rocket & Gym",subtitle:"Team Rocket • Gym Challenge"}];
const OWNED_KEY="pokemonTrackerOwned";
let owned={};try{owned=JSON.parse(localStorage.getItem(OWNED_KEY)||"{}")||{}}catch{owned={}}
let cards=[],filter="all",page=0,setFilters=["all","all"],market=false;
const $=id=>document.getElementById(id);
const save=()=>localStorage.setItem(OWNED_KEY,JSON.stringify(owned));
const key=c=>c.id;
const pageCards=p=>cards.filter(c=>SETS.find(s=>s.id===c.set)?.page===p);
function stats(){const total=cards.length,own=cards.filter(c=>owned[key(c)]).length;$("ownedCount").textContent=own;$("totalCount").textContent=total;$("percent").textContent=total?Math.round(own/total*100)+"%":"0%"}
function renderTabs(p){const sets=SETS.filter(s=>s.page===p);$("setTabs"+p).innerHTML=[["all","All Sets"],...sets.map(s=>[s.id,s.name])].map(([id,n])=>\`<button data-set="\${id}" class="\${setFilters[p]===id?"active":""}">\${n}</button>\`).join("");$("setTabs"+p).querySelectorAll("[data-set]").forEach(b=>b.onclick=()=>{setFilters[p]=b.dataset.set;renderTabs(p);renderPage(p)})}
function renderProgress(p){const sets=SETS.filter(s=>s.page===p);$("setProgress"+p).style.gridTemplateColumns="repeat("+sets.length+",minmax(0,1fr))";$("setProgress"+p).innerHTML=sets.map(s=>{const a=cards.filter(c=>c.set===s.id),o=a.filter(c=>owned[key(c)]).length,pct=a.length?Math.round(o/a.length*100):0;return \`<div class="set-box"><strong>\${s.name}: \${o}/\${a.length}</strong><div class="bar"><i style="width:\${pct}%"></i></div></div>\`}).join("")}
function filtered(p){const q=$("search").value.trim().toLowerCase();return pageCards(p).filter(c=>(setFilters[p]==="all"||c.set===setFilters[p])&&(!q||c.name.toLowerCase().includes(q)||String(c.dex)===q||c.number.toLowerCase()===q)).filter(c=>filter==="all"||(filter==="owned"?owned[key(c)]:!owned[key(c)]))}
function renderPage(p){renderProgress(p);const list=filtered(p),totalPage=pageCards(p).length,ownedPage=pageCards(p).filter(c=>owned[key(c)]).length;$("status"+p).textContent=list.length===totalPage?\`\${totalPage} Pokémon cards on this page.\`:\`\${list.length} cards shown • \${ownedPage}/\${totalPage} owned\`;$("grid"+p).innerHTML=list.length?list.map(c=>\`<article class="card \${owned[key(c)]?"owned":"missing"}" data-id="\${c.id}"><button class="check" aria-label="Toggle \${c.name} ownership">\${owned[key(c)]?"✓":"+"}</button><img loading="lazy" src="\${c.image}" alt="\${c.name}"><div class="info"><div class="name">#\${c.dex} \${c.name}</div><div class="meta">\${c.setName} • #\${c.number}</div></div></article>\`).join(""):\`<div class="empty">No cards match your filters.</div>\`;document.querySelectorAll("#grid"+p+" .card").forEach(el=>el.onclick=()=>{const id=el.dataset.id;owned[id]=!owned[id];if(!owned[id])delete owned[id];save();render()})}
function updatePager(){$("pager").style.transform=\`translateX(-\${page*50}%)\`;$("pageTitle").textContent=PAGES[page].title;$("pageSubtitle").textContent=PAGES[page].subtitle;$("pageIndicator").textContent=(page+1)+" of "+PAGES.length;$("prevPage").disabled=page===0;$("nextPage").disabled=page===PAGES.length-1;$("prevPage").style.opacity=page===0?".35":"1";$("nextPage").style.opacity=page===PAGES.length-1?".35":"1"}
function setPage(p){p=Math.max(0,Math.min(PAGES.length-1,p));if(p===page)return;page=p;updatePager()}
function render(){stats();renderPage(0);renderPage(1);updatePager()}
async function load(){try{const [a,b]=await Promise.all([fetch("./cards.json",{cache:"no-store"}),fetch("./expansions.json",{cache:"no-store"})]);if(!a.ok||!b.ok)throw Error();cards=[...(await a.json()),...(await b.json())];cards.sort((a,b)=>a.dex-b.dex||SETS.findIndex(s=>s.id===a.set)-SETS.findIndex(s=>s.id===b.set)||Number(a.number)-Number(b.number));renderTabs(0);renderTabs(1);render()}catch(e){console.error(e);$("status0").textContent="Could not load the card catalog. Please refresh the app while online.";$("status1").textContent="Could not load the card catalog. Please refresh the app while online."}}
async function prepareOffline(){if(!cards.length)return;$("offlineBtn").textContent="Preparing…";let ok=0;const cache=await caches.open("pokemon-tracker-images-v3");for(const c of cards){try{const r=await fetch(c.image,{cache:"reload"});if(r.ok){await cache.put(c.image,r.clone());ok++}}catch{}}$("offlineBtn").textContent="Offline Ready ✓";$("status"+page).textContent=\`Offline package ready: \${ok}/\${cards.length} card images cached.\`}
function backup(){const payload={app:"Pokemon Card Tracker",version:3,exportedAt:new Date().toISOString(),owned};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="pokemon-tracker-backup.json";a.click();URL.revokeObjectURL(a.href);$("status"+page).textContent="Backup file created."}
function restore(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data.owned||typeof data.owned!=="object")throw Error();owned=data.owned;save();render();$("status"+page).textContent="Collection restored successfully."}catch{$("status"+page).textContent="That backup file could not be restored."}};reader.readAsText(file)}
function toggleMarket(){market=!market;document.body.classList.toggle("market",market);$("marketBtn").textContent=market?"Exit Market Mode":"Market Mode";$("footer").textContent=market?"Market Mode: tap a card row to mark it owned. Swipe left/right to switch set pages.":"Swipe left/right to switch set pages. Your collection is saved on this device.";if(market){filter="missing";document.querySelectorAll("[data-filter]").forEach(b=>b.classList.toggle("active",b.dataset.filter==="missing"));$("search").focus()}render()}
$("search").addEventListener("input",render);document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));render()});$("offlineBtn").onclick=prepareOffline;$("backupBtn").onclick=backup;$("restoreBtn").onclick=()=>$("restoreInput").click();$("restoreInput").onchange=e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=""};$("marketBtn").onclick=toggleMarket;$("prevPage").onclick=()=>setPage(page-1);$("nextPage").onclick=()=>setPage(page+1);
let touchX=0,touchY=0;$("pagerViewport").addEventListener("touchstart",e=>{touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY},{passive:true});$("pagerViewport").addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)*1.2)setPage(page+(dx<0?1:-1))},{passive:true});
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});load();