const SETS=[{id:"base1",name:"Base",page:0},{id:"base2",name:"Jungle",page:0},{id:"base3",name:"Fossil",page:0},{id:"base5",name:"Team Rocket",page:1},{id:"gym2",name:"Gym Challenge",page:1},{id:"gym1",name:"Gym Heroes",page:1}];
const EXTRA_ORDER=["base1","base2","base3","base5","gym1","gym2"];const EXTRA_SETS=EXTRA_ORDER.map(id=>({...SETS.find(s=>s.id===id),page:2}));
const PAGES=[{title:"Classic Sets",subtitle:"Base • Jungle • Fossil"},{title:"Rocket & Gym",subtitle:"Team Rocket • Gym Challenge • Gym Heroes"},{title:"Trainers & Energy",subtitle:"All six tracked sets"}];
const OWNED_KEY="pokemonTrackerOwned";const PRICE_KEY="pokemonTrackerPriceApiKey";const PRICE_CACHE_KEY="pokemonTrackerPriceCacheV1";const PRICE_CACHE_TTL=12*60*60*1000;const PRICE_API="https://api.pkmnprices.com/v1";const CONDITION_ORDER=["Near Mint","Lightly Played","Moderately Played","Heavily Played","Damaged"];const SET_TOTALS={base1:"102",base2:"64",base3:"62",base5:"83",gym1:"132",gym2:"132"};const PRICING_SET_NAMES={base1:"Base Set",base2:"Jungle",base3:"Fossil",base5:"Team Rocket",gym1:"Gym Heroes",gym2:"Gym Challenge"};let priceCache={};try{priceCache=JSON.parse(localStorage.getItem(PRICE_CACHE_KEY)||"{}")||{}}catch{priceCache={}}
let owned={};try{owned=JSON.parse(localStorage.getItem(OWNED_KEY)||"{}")||{}}catch{owned={}}
let cards=[],extraCards=[],filter="all",page=0,setFilters=["all","all","all"],market=false;
const $=id=>document.getElementById(id); const save=()=>localStorage.setItem(OWNED_KEY,JSON.stringify(owned)); const key=c=>c.id;
const IMAGE_SET_SLUG={base1:"base",base2:"jungle",base3:"fossil",base5:"teamrocket",gym1:"gymheroes",gym2:"gymchallenge"};
const fallbackImage=c=>"https://www.serebii.net/card/"+IMAGE_SET_SLUG[c.set]+"/"+String(c.number).padStart(3,"0")+".jpg";
function resizePager(){requestAnimationFrame(()=>{const el=document.querySelectorAll(".page")[page];if(el) $("pagerViewport").style.height=el.scrollHeight+"px"})}
const setsForPage=p=>p===2?EXTRA_SETS:SETS.filter(s=>s.page===p);
const pageCards=p=>p===2?extraCards:cards.filter(c=>SETS.find(s=>s.id===c.set)?.page===p);
function stats(){const current=pageCards(page),total=current.length,own=current.filter(c=>owned[key(c)]).length;$("ownedCount").textContent=own;$("totalCount").textContent=total;$("percent").textContent=total?Math.round(own/total*100)+"%":"0%"}
function renderTabs(p){const sets=setsForPage(p);$("setTabs"+p).innerHTML=[["all","All Sets"],...sets.map(s=>[s.id,s.name])].map(x=>'<button data-set="'+x[0]+'" class="'+(setFilters[p]===x[0]?"active":"")+'">'+x[1]+"</button>").join("");$("setTabs"+p).querySelectorAll("[data-set]").forEach(b=>b.onclick=()=>{setFilters[p]=b.dataset.set;renderTabs(p);renderPage(p);if(p===page)resizePager()})}
function renderProgress(p){const sets=setsForPage(p);$("setProgress"+p).style.gridTemplateColumns="repeat("+sets.length+",minmax(0,1fr))";$("setProgress"+p).innerHTML=sets.map(s=>{const a=pageCards(p).filter(c=>c.set===s.id),o=a.filter(c=>owned[key(c)]).length,pct=a.length?Math.round(o/a.length*100):0;return '<div class="set-box"><strong>'+s.name+": "+o+"/"+a.length+'</strong><div class="bar"><i style="width:'+pct+'%"></i></div></div>'}).join("")}
function filtered(p){const q=$("search").value.trim().toLowerCase();return pageCards(p).filter(c=>(setFilters[p]==="all"||c.set===setFilters[p])&&(!q||c.name.toLowerCase().includes(q)||String(c.number)===q||(p<2&&String(c.dex)===q))).filter(c=>filter==="all"||(filter==="owned"?owned[key(c)]:!owned[key(c)]))}
function cardMarkup(c){const fallback=fallbackImage(c);return `<article class="card ${owned[key(c)]?"owned":"missing"}" data-id="${c.id}" tabindex="0" role="button" aria-label="Open details for ${c.name}"><img loading="lazy" src="${c.image}" alt="${c.name}" onerror="this.onerror=null;this.src='${fallback}'"><div class="info"><div class="name">#${c.number} ${c.name}</div><div class="meta">${c.setName} • ${c.category}</div></div><div class="card-state">${owned[key(c)]?"✓ Collected":"Tap for details"}</div></article>`}
function renderPage(p){renderProgress(p);const list=filtered(p),totalPage=pageCards(p).length,ownedPage=pageCards(p).filter(c=>owned[key(c)]).length,label=p===2?"Trainer/Energy cards":"Pokémon cards";$("status"+p).textContent=list.length===totalPage?totalPage+" "+label+" on this page.":list.length+" cards shown • "+ownedPage+"/"+totalPage+" owned";$("grid"+p).innerHTML=list.length?list.map(cardMarkup).join(""):'<div class="empty">No cards match your filters.</div>';document.querySelectorAll("#grid"+p+" .card").forEach(el=>{el.onclick=()=>openCard(el.dataset.id);el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openCard(el.dataset.id)}}})}
function updatePager(){$("pager").style.transform="translateX(-"+page*(100/PAGES.length)+"%)";$("pageTitle").textContent=PAGES[page].title;$("pageSubtitle").textContent=PAGES[page].subtitle;$("pageIndicator").textContent=(page+1)+" of "+PAGES.length;$("prevPage").disabled=page===0;$("nextPage").disabled=page===PAGES.length-1;$("prevPage").style.opacity=page===0?".35":"1";$("nextPage").style.opacity=page===PAGES.length-1?".35":"1"}
function setPage(p){p=Math.max(0,Math.min(PAGES.length-1,p));if(p===page)return;page=p;updatePager();stats();resizePager()}
function render(){stats();for(let p=0;p<PAGES.length;p++)renderPage(p);updatePager();resizePager()}
async function load(){try{const [a,b,c]=await Promise.all([fetch("./cards.json",{cache:"no-store"}),fetch("./expansions.json",{cache:"no-store"}),fetch("./extras.json",{cache:"no-store"})]);if(!a.ok||!b.ok||!c.ok)throw Error();cards=[...(await a.json()),...(await b.json())];extraCards=await c.json();if(owned["extra-base5-80"]&&!owned["extra-base5-17"]){owned["extra-base5-17"]=true;delete owned["extra-base5-80"]}if(owned["extra-base5-71"]&&!owned["extra-base5-15"]){owned["extra-base5-15"]=true;delete owned["extra-base5-71"]}if(owned["extra-base5-72"]&&!owned["extra-base5-16"]){owned["extra-base5-16"]=true;delete owned["extra-base5-72"]}if(owned["extra-gym2-100"]&&!owned["extra-gym2-17"]){owned["extra-gym2-17"]=true;delete owned["extra-gym2-100"]}if(owned["extra-gym2-104"]&&!owned["extra-gym2-18"]){owned["extra-gym2-18"]=true;delete owned["extra-gym2-104"]}if(owned["extra-gym2-106"]&&!owned["extra-gym2-19"]){owned["extra-gym2-19"]=true;delete owned["extra-gym2-106"]}if(owned["extra-gym2-110"]&&!owned["extra-gym2-20"]){owned["extra-gym2-20"]=true;delete owned["extra-gym2-110"]}save();cards.sort((a,b)=>a.dex-b.dex||SETS.findIndex(s=>s.id===a.set)-SETS.findIndex(s=>s.id===b.set)||Number(a.number)-Number(b.number));extraCards.sort((a,b)=>{const ac=a.category==="Energy"?0:1,bc=b.category==="Energy"?0:1;return ac-bc||EXTRA_ORDER.indexOf(a.set)-EXTRA_ORDER.indexOf(b.set)||Number(a.number)-Number(b.number)});for(let p=0;p<PAGES.length;p++)renderTabs(p);render()}catch(e){console.error(e);for(let p=0;p<PAGES.length;p++)$("status"+p).textContent="Could not load the card catalog. Please refresh the app while online."}}
async function prepareOffline(){const all=[...cards,...extraCards];if(!all.length)return;$("offlineBtn").textContent="Preparing…";let ok=0;const cache=await caches.open("pokemon-tracker-images-v3");for(const c of all){try{const r=await fetch(c.image,{cache:"reload"});if(r.ok){await cache.put(c.image,r.clone());ok++}}catch{}}$("offlineBtn").textContent="Offline Ready ✓";$("status"+page).textContent="Offline package ready: "+ok+"/"+all.length+" card images cached."}
function backup(){const payload={app:"Pokemon Card Tracker",version:4,exportedAt:new Date().toISOString(),owned};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="pokemon-tracker-backup.json";a.click();URL.revokeObjectURL(a.href);$("status"+page).textContent="Backup file created."}
function restore(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data.owned||typeof data.owned!=="object")throw Error();owned=data.owned;save();render();$("status"+page).textContent="Collection restored successfully."}catch{$("status"+page).textContent="That backup file could not be restored."}};reader.readAsText(file)}
function priceApiKey(){return localStorage.getItem(PRICE_KEY)||""}
function savePriceApiKey(v){if(v)localStorage.setItem(PRICE_KEY,v.trim());else localStorage.removeItem(PRICE_KEY)}
function priceCacheSave(){localStorage.setItem(PRICE_CACHE_KEY,JSON.stringify(priceCache))}
function priceSetId(c){return c.set==="fossil"?"base3":c.set}
function preferredVariant(variants){const names=variants.map(v=>v.variant);const wanted=["Normal","Unlimited","Holofoil","Reverse Holofoil"];for(const w of wanted){const hit=names.find(n=>n===w);if(hit)return hit}return names[0]||""}
function formatPrice(v){return typeof v==="number"?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v):"—"}
function cacheEntry(c){const e=priceCache[c.id];return e&&Date.now()-e.fetchedAt<PRICE_CACHE_TTL?e:null}
async function findPriceCard(c,keyValue){const params=new URLSearchParams({name:c.name,number:String(c.number),total_set_number:SET_TOTALS[priceSetId(c)],per_page:"20"});const r=await fetch(PRICE_API+"/cards?"+params.toString(),{headers:{"X-API-Key":keyValue},cache:"no-store"});if(!r.ok)throw Error("Search failed ("+r.status+")");const data=await r.json();const exact=(data.data||[]).find(x=>x.set&&x.set.name===PRICING_SET_NAMES[priceSetId(c)])||(data.data||[])[0];if(!exact)throw Error("Card not found");return exact}
async function loadPrices(c){const keyValue=priceApiKey();if(!keyValue)throw Error("NO_KEY");const cached=cacheEntry(c);if(cached)return cached;const found=await findPriceCard(c,keyValue);const r=await fetch(PRICE_API+"/cards/"+found.id+"?currency=usd",{headers:{"X-API-Key":keyValue},cache:"no-store"});if(!r.ok)throw Error("Price lookup failed ("+r.status+")");const data=await r.json();const entry={fetchedAt:Date.now(),apiId:found.id,prices:data.prices||[],name:data.name,set:data.set};priceCache[c.id]=entry;priceCacheSave();return entry}
function variantPrices(entry,variant){return CONDITION_ORDER.map(condition=>entry.prices.find(p=>p.source==="tcgplayer"&&p.currency==="USD"&&p.condition===condition&&p.variant===variant)||null)}
function renderPriceRows(entry,variant){const rows=variantPrices(entry,variant);$("priceRows").innerHTML=rows.map((p,i)=>`<div class="price-row"><span class="price-condition">${CONDITION_ORDER[i]}</span><span class="${p&&p.market_price!=null?"price-value":"price-missing"}">${p&&p.market_price!=null?formatPrice(p.market_price):"No market data"}</span></div>`).join("")}
function populateVariants(entry){const variants=[...new Set(entry.prices.filter(p=>p.source==="tcgplayer"&&p.currency==="USD").map(p=>p.variant).filter(Boolean))];const select=$("priceVariant");select.innerHTML=variants.length?variants.map(v=>`<option>${v}</option>`).join(""):'<option>No pricing variant found</option>';const chosen=preferredVariant(variants.map(v=>({variant:v})));if(chosen)select.value=chosen;select.onchange=()=>renderPriceRows(entry,select.value);if(variants.length)renderPriceRows(entry,select.value);else $("priceRows").innerHTML='<div class="price-loading">No TCGplayer market data is available for this card.</div>'}
function setModalOwned(c){const b=$("modalOwned");const isOwned=!!owned[key(c)];b.textContent=isOwned?"✓ Collected — Tap to remove":"＋ Add to collection";b.classList.toggle("owned",isOwned)}
function showPriceSetup(){const hasKey=!!priceApiKey();$("priceSetup").style.display=hasKey?"none":"block";$("priceApiKey").value="";$("settingsApiKey").value="";$("settingsApiKey").placeholder=hasKey?"Saved key":"pk_..."}
function openModal(el){el.classList.add("open");el.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function closeModalById(id){const el=$(id);el.classList.remove("open");el.setAttribute("aria-hidden","true");if(!document.querySelector(".modal.open"))document.body.style.overflow=""}
let activeCard=null;
async function openCard(id){const c=[...cards,...extraCards].find(x=>x.id===id);if(!c)return;activeCard=c;$("modalImage").src=c.image;$("modalImage").alt=c.name;$("modalTitle").textContent="#"+c.number+" "+c.name;$("modalMeta").textContent=c.setName+" • "+(c.category||"Pokémon")+(c.dex?" • National Dex #"+c.dex:"");setModalOwned(c);$("priceRows").innerHTML='<div class="price-loading">Loading current market prices…</div>';$("priceUpdated").textContent="";$("priceSource").textContent="";showPriceSetup();openModal($("cardModal"));try{const entry=await loadPrices(c);populateVariants(entry);const when=new Date(entry.prices.find(p=>p.source==="tcgplayer")?.created_at||entry.fetchedAt);$("priceUpdated").textContent="Updated "+when.toLocaleDateString();$("priceSource").textContent="Source: TCGplayer market data via PkmnPrices. Prices vary by condition and printing; use the copy's actual printing when it matters."}catch(e){$("priceRows").innerHTML=e.message==="NO_KEY"?'<div class="price-loading">Pricing is ready once you add your PkmnPrices API key below.</div>':'<div class="price-loading">Could not load pricing. Check your key or try again while online.</div>';}}
$("modalOwned").onclick=()=>{if(!activeCard)return;const id=key(activeCard);if(owned[id])delete owned[id];else owned[id]=true;save();setModalOwned(activeCard);render();};
$("closeModal").onclick=()=>closeModalById("cardModal");document.querySelector('[data-close-modal]').onclick=()=>closeModalById("cardModal");
$("savePriceKey").onclick=()=>{savePriceApiKey($("priceApiKey").value);showPriceSetup();if(activeCard)openCard(activeCard.id)};
$("priceSettingsBtn").onclick=()=>{showPriceSetup();openModal($("priceSettingsModal"))};
$("closePriceSettings").onclick=()=>closeModalById("priceSettingsModal");document.querySelector('[data-close-price-settings]').onclick=()=>closeModalById("priceSettingsModal");
$("saveSettingsKey").onclick=()=>{savePriceApiKey($("settingsApiKey").value);closeModalById("priceSettingsModal");if(activeCard)openCard(activeCard.id)};
$("clearSettingsKey").onclick=()=>{savePriceApiKey("");showPriceSetup();};
$("priceApiKey").addEventListener("keydown",e=>{if(e.key==="Enter")$("savePriceKey").click()});$("settingsApiKey").addEventListener("keydown",e=>{if(e.key==="Enter")$("saveSettingsKey").click()});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModalById("cardModal");closeModalById("priceSettingsModal")}});
function toggleMarket(){market=!market;document.body.classList.toggle("market",market);$("marketBtn").textContent=market?"Exit Market Mode":"Market Mode";$("footer").textContent=market?"Market Mode: tap a card row to open details and mark it owned. Swipe left/right to switch pages.":"Swipe left/right to switch pages. Your collection is saved on this device.";if(market){filter="missing";document.querySelectorAll("[data-filter]").forEach(b=>b.classList.toggle("active",b.dataset.filter==="missing"));$("search").focus()}render()}
$("search").addEventListener("input",render);document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));render()});$("offlineBtn").onclick=prepareOffline;$("backupBtn").onclick=backup;$("restoreBtn").onclick=()=>$("restoreInput").click();$("restoreInput").onchange=e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=""};$("marketBtn").onclick=toggleMarket;$("prevPage").onclick=()=>setPage(page-1);$("nextPage").onclick=()=>setPage(page+1);
let touchX=0,touchY=0;$("pagerViewport").addEventListener("touchstart",e=>{touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY},{passive:true});window.addEventListener("resize",resizePager);$("pagerViewport").addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)*1.2)setPage(page+(dx<0?1:-1))},{passive:true});
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});load();
