const SETS=[{id:"base1",name:"Base"},{id:"base2",name:"Jungle"},{id:"base3",name:"Fossil"}];
const OWNED_KEY="pokemonTrackerOwned";
let owned={};try{owned=JSON.parse(localStorage.getItem(OWNED_KEY)||"{}")||{}}catch{owned={}}
let cards=[],filter="all",setFilter="all",market=false;
const $=id=>document.getElementById(id);
const save=()=>localStorage.setItem(OWNED_KEY,JSON.stringify(owned));
const key=c=>c.id;
function stats(){const total=cards.length,own=cards.filter(c=>owned[key(c)]).length;$("ownedCount").textContent=own;$("totalCount").textContent=total;$("percent").textContent=total?Math.round(own/total*100)+"%":"0%";
$("setProgress").innerHTML=SETS.map(s=>{const a=cards.filter(c=>c.set===s.id),o=a.filter(c=>owned[key(c)]).length,p=a.length?Math.round(o/a.length*100):0;return `<div class="set-box"><strong>${s.name}: ${o}/${a.length}</strong><div class="bar"><i style="width:${p}%"></i></div></div>`}).join("")}
function renderTabs(){$("setTabs").innerHTML=[["all","All Sets"],...SETS.map(s=>[s.id,s.name])].map(([id,n])=>`<button data-set="${id}" class="${setFilter===id?"active":""}">${n}</button>`).join("");document.querySelectorAll("[data-set]").forEach(b=>b.onclick=()=>{setFilter=b.dataset.set;renderTabs();render()})}
function filtered(){const q=$("search").value.trim().toLowerCase();return cards.filter(c=>(setFilter==="all"||c.set===setFilter)&&(!q||c.name.toLowerCase().includes(q)||String(c.dex)===q||c.number.toLowerCase().includes(q))).filter(c=>filter==="all"||(filter==="owned"?owned[key(c)]:!owned[key(c)]))}
function render(){stats();const list=filtered();$("status").textContent=list.length===cards.length?`${cards.length} Pokémon cards in your catalog.`: `${list.length} cards shown • ${cards.filter(c=>owned[key(c)]).length}/${cards.length} owned`;$("grid").innerHTML=list.length?list.map(c=>`<article class="card ${owned[key(c)]?"owned":"missing"}" data-id="${c.id}"><button class="check" aria-label="Toggle ${c.name} ownership">${owned[key(c)]?"✓":"+"}</button><img loading="lazy" src="${c.image}" alt="${c.name}"><div class="info"><div class="name">#${c.dex} ${c.name}</div><div class="meta">${c.setName} • #${c.number}</div></div></article>`).join(""):`<div class="empty">No cards match your filters.</div>`;document.querySelectorAll(".card").forEach(el=>el.onclick=()=>{const id=el.dataset.id;owned[id]=!owned[id];if(!owned[id])delete owned[id];save();render()})}
async function load(){try{const res=await fetch("./cards.json",{cache:"no-store"});if(!res.ok)throw Error();cards=await res.json();cards.sort((a,b)=>a.dex-b.dex||SETS.findIndex(s=>s.id===a.set)-SETS.findIndex(s=>s.id===b.set));$("status").textContent=`${cards.length} Pokémon cards loaded.`;renderTabs();render()}catch(e){$("status").textContent="Offline catalog unavailable. Open the app once while online, then use Prepare Offline."}}
async function prepareOffline(){if(!cards.length)return;$("offlineBtn").textContent="Preparing…";let ok=0;const cache=await caches.open("pokemon-tracker-images-v3");for(const c of cards){try{const r=await fetch(c.image,{cache:"reload"});if(r.ok){await cache.put(c.image,r.clone());ok++}}catch{}}$("offlineBtn").textContent="Offline Ready ✓";$("status").textContent=`Offline package ready: ${ok}/${cards.length} card images cached.`}
function backup(){const payload={app:"Pokemon Card Tracker",version:2,exportedAt:new Date().toISOString(),owned};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="pokemon-tracker-backup.json";a.click();URL.revokeObjectURL(a.href);$("status").textContent="Backup file created."}
function restore(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data.owned||typeof data.owned!=="object")throw Error();owned=data.owned;save();render();$("status").textContent="Collection restored successfully."}catch{$("status").textContent="That backup file could not be restored."}};reader.readAsText(file)}
function toggleMarket(){market=!market;document.body.classList.toggle("market",market);$("marketBtn").textContent=market?"Exit Market Mode":"Market Mode";$("footer").textContent=market?"Market Mode: tap a card row to mark it owned. Search is optimized for quick checks.":"Your collection is saved on this device. Prepare Offline before flea markets.";if(market){filter="missing";document.querySelectorAll("[data-filter]").forEach(b=>b.classList.toggle("active",b.dataset.filter==="missing"));$("search").focus();render()}else render()}
$("search").addEventListener("input",render);document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));render()});$("offlineBtn").onclick=prepareOffline;$("backupBtn").onclick=backup;$("restoreBtn").onclick=()=>$("restoreInput").click();$("restoreInput").onchange=e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=""};$("marketBtn").onclick=toggleMarket;
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});load();